package github

import (
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/saltyorg/docs-automation/health"
)

const (
	issueVisibleFindingLimit = 100
	issueRedactedPathLabel   = "(redacted path)"
)

// IssueRenderer renders documentation-health reports without GitHub side effects.
type IssueRenderer struct {
	docsRepository string
}

// NewIssueRenderer creates a renderer for the configured Docs repository slug.
func NewIssueRenderer(docsRepository string) *IssueRenderer {
	return &IssueRenderer{docsRepository: docsRepository}
}

// Title renders severity-aware issue title text.
func (r *IssueRenderer) Title(report health.Report) string {
	parts := make([]string, 0, 2)
	if count := report.TotalSeverity(health.Error); count > 0 {
		parts = append(parts, countWithNoun(count, "error"))
	}
	if count := report.TotalSeverity(health.Notice); count > 0 {
		parts = append(parts, countWithNoun(count, "notice"))
	}
	if len(parts) == 0 {
		return "[Docs Health] healthy"
	}
	return "[Docs Health] " + strings.Join(parts, ", ")
}

// Body renders a complete human-readable report and its semantic state marker.
func (r *IssueRenderer) Body(report health.Report) (string, error) {
	report = report.Canonical()
	marker, err := encodeIssueState(issueStateForReport(report))
	if err != nil {
		return "", fmt.Errorf("rendering issue state: %w", err)
	}

	var body strings.Builder
	body.WriteString("> [!IMPORTANT]\n")
	body.WriteString("> This issue is regenerated by sb-docs. Fix the linked source, documentation,\n")
	body.WriteString("> or coverage configuration; manual task state is not retained.\n\n")
	body.WriteString("| Check | Status | Findings | Exemptions |\n")
	body.WriteString("|---|---:|---:|---:|\n")
	for _, result := range report.Results {
		status := "Disabled"
		exemptions := "—"
		if result.Enabled {
			exemptions = fmt.Sprintf("%d", result.Exemptions)
			status = "Passed"
			if len(result.Findings) > 0 {
				status = "Action required"
			}
		}
		fmt.Fprintf(&body, "| %s | %s | %d | %s |\n",
			markdownIssueText(issueResultLabel(result.Kind)), status, len(result.Findings), exemptions)
	}
	body.WriteString("\n")

	sources := sourceRevisionMap(report.Run.Sources)
	for _, result := range report.Results {
		if !result.Enabled || len(result.Findings) == 0 {
			continue
		}
		r.writeResultDetails(&body, result, report.Run, sources)
	}

	writeRunContext(&body, report.Run)
	body.WriteString("\n")
	body.WriteString(marker)
	body.WriteString("\n")
	return body.String(), nil
}

func (r *IssueRenderer) writeResultDetails(
	body *strings.Builder,
	result health.Result,
	run health.RunInfo,
	sources map[string]health.SourceRevision,
) {
	wrapped := len(result.Findings) > 10
	label := markdownIssueText(issueResultLabel(result.Kind))
	if wrapped {
		body.WriteString("<details>\n")
		fmt.Fprintf(body, "<summary>%s (%d)</summary>\n\n", label, len(result.Findings))
	} else {
		fmt.Fprintf(body, "### %s (%d)\n\n", label, len(result.Findings))
	}
	body.WriteString(issueRemediation(result.Kind))
	body.WriteString("\n\n")
	body.WriteString("| Repository | Subject | Source | Docs | Detail |\n")
	body.WriteString("|---|---|---|---|---|\n")

	visible := min(len(result.Findings), issueVisibleFindingLimit)
	for _, finding := range result.Findings[:visible] {
		fmt.Fprintf(body, "| %s | %s | %s | %s | %s |\n",
			markdownIssueText(finding.Repository),
			markdownIssueText(issueFindingLabel(finding)),
			r.sourceCell(finding, sources),
			r.docsCell(result.Kind, finding.Path, run.Branch),
			markdownIssueText(finding.Detail),
		)
	}
	if omitted := len(result.Findings) - visible; omitted > 0 {
		fmt.Fprintf(body, "\n%d additional findings omitted; view the complete Actions summary.\n", omitted)
	}
	body.WriteString("\n")
	if wrapped {
		body.WriteString("</details>\n\n")
	}
}

func issueFindingLabel(finding health.Finding) string {
	label := finding.Label()
	if finding.Subject == "" && absoluteIssuePath(label) {
		return issueRedactedPathLabel
	}
	return label
}

func issueStateForReport(report health.Report) health.State {
	state := report.State()
	unsafeIDs := make(map[string]struct{})
	for _, result := range report.Results {
		for _, finding := range result.Findings {
			if finding.Subject == "" && absoluteIssuePath(finding.Label()) {
				unsafeIDs[finding.ID()] = struct{}{}
			}
		}
	}
	for resultIndex := range state.Results {
		for findingIndex := range state.Results[resultIndex].Findings {
			finding := &state.Results[resultIndex].Findings[findingIndex]
			if _, unsafe := unsafeIDs[finding.ID]; unsafe {
				finding.Label = issueRedactedPathLabel
			}
		}
	}
	return state
}

func (r *IssueRenderer) sourceCell(finding health.Finding, sources map[string]health.SourceRevision) string {
	if finding.Kind == health.OrphanedDocumentation {
		return "—"
	}
	if !safeIssuePath(finding.SourcePath) {
		return "—"
	}
	source, configured := sources[finding.Repository]
	if !configured || source.Slug == "" {
		return markdownIssueCode(finding.SourcePath)
	}
	revision := source.Revision
	if revision == "" {
		revision = source.Ref
	}
	if revision == "" {
		return markdownIssueCode(finding.SourcePath)
	}
	return "[View source](" + githubIssueURL(source.Slug, "tree", revision, finding.SourcePath) + ")"
}

func (r *IssueRenderer) docsCell(kind health.Kind, docsPath, branch string) string {
	if !safeIssuePath(docsPath) {
		return "—"
	}
	if kind == health.MissingDocumentation || r.docsRepository == "" || branch == "" {
		return markdownIssueCode(docsPath)
	}
	return "[Open Docs page](" + githubIssueURL(r.docsRepository, "blob", branch, docsPath) + ")"
}

func writeRunContext(body *strings.Builder, run health.RunInfo) {
	body.WriteString("## Run context\n\n")
	checkedAt := "unknown"
	if !run.CheckedAt.IsZero() {
		checkedAt = run.CheckedAt.UTC().Format("2006-01-02 15:04:05 UTC")
	}
	fmt.Fprintf(body, "- Checked at: %s\n", checkedAt)
	if run.WorkflowURL != "" {
		fmt.Fprintf(body, "- Workflow: [View this documentation-health workflow run](%s)\n", escapeIssueLinkURL(run.WorkflowURL))
	} else {
		body.WriteString("- Workflow: unavailable\n")
	}
	fmt.Fprintf(body, "- Docs branch: %s\n", markdownIssueText(run.Branch))
	fmt.Fprintf(body, "- sb-docs: %s\n", markdownIssueText(run.Version))
	if len(run.Sources) == 0 {
		return
	}
	body.WriteString("- Source revisions:\n")
	for _, source := range run.Sources {
		revision := source.Revision
		if revision == "" {
			revision = source.Ref
		}
		label := markdownIssueText(revision)
		if source.Slug == "" || revision == "" {
			fmt.Fprintf(body, "  - %s: %s\n", markdownIssueText(source.Repository), label)
			continue
		}
		fmt.Fprintf(body, "  - %s: [%s](%s)\n",
			markdownIssueText(source.Repository), label, githubIssueURL(source.Slug, "tree", revision, ""))
	}
}

func issueRemediation(kind health.Kind) string {
	switch kind {
	case health.RoleAutomationError, health.CLIHelpAutomationError:
		return "Inspect the linked workflow and resolve the automation error."
	case health.MissingDocumentation:
		return "Create the expected standalone Docs page, document a helper role under its parent page and explicitly exclude the helper, or intentionally exclude the role from coverage."
	case health.MissingVariablesSection:
		return "Restore the managed variables section, or disable that section's automation for the page."
	case health.MissingOverviewSection:
		return "Restore the managed overview section, or disable that section's automation for the page."
	case health.OrphanedDocumentation:
		return "Remove the orphaned Docs page, map it to the correct source role, or intentionally exclude it from coverage."
	case health.InvalidFrontmatter:
		return "Correct or omit invalid optional metadata, disable automation for the page, or exclude its path from this check."
	case health.EditorialAttention:
		return "Resolve the editorial status, or deliberately clear, disable, or path-exclude it."
	default:
		return "Resolve the finding or intentionally exclude it from this check."
	}
}

func issueResultLabel(kind health.Kind) string {
	switch kind {
	case health.RoleAutomationError:
		return "Role Automation Errors"
	case health.CLIHelpAutomationError:
		return "CLI Help Automation Errors"
	case health.MissingDocumentation:
		return "Missing Documentation"
	case health.InvalidFrontmatter:
		return "Invalid Frontmatter"
	case health.MissingVariablesSection:
		return "Missing Variables Sections"
	case health.MissingOverviewSection:
		return "Missing Overview Sections"
	case health.OrphanedDocumentation:
		return "Orphaned Documentation"
	case health.EditorialAttention:
		return "Editorial Attention"
	default:
		return string(kind)
	}
}

func countWithNoun(count int, noun string) string {
	if count != 1 {
		noun += "s"
	}
	return fmt.Sprintf("%d %s", count, noun)
}

func sourceRevisionMap(sources []health.SourceRevision) map[string]health.SourceRevision {
	byRepository := make(map[string]health.SourceRevision, len(sources))
	for _, source := range sources {
		byRepository[source.Repository] = source
	}
	return byRepository
}

func githubIssueURL(slug, operation, revision, relativePath string) string {
	segments := []string{"https://github.com"}
	segments = append(segments, escapedIssueSegments(slug)...)
	segments = append(segments, url.PathEscape(operation), url.PathEscape(revision))
	segments = append(segments, escapedIssueSegments(relativePath)...)
	return strings.Join(segments, "/")
}

func escapedIssueSegments(value string) []string {
	if value == "" {
		return nil
	}
	parts := strings.Split(strings.ReplaceAll(value, "\\", "/"), "/")
	escaped := make([]string, 0, len(parts))
	for _, part := range parts {
		if part != "" {
			escaped = append(escaped, url.PathEscape(part))
		}
	}
	return escaped
}

func safeIssuePath(value string) bool {
	if value == "" || absoluteIssuePath(value) {
		return false
	}
	if len(value) >= 2 && value[1] == ':' {
		return false
	}
	for _, segment := range strings.Split(strings.ReplaceAll(value, "\\", "/"), "/") {
		if segment == "" || segment == "." || segment == ".." {
			return false
		}
	}
	return path.Clean(value) != "."
}

func absoluteIssuePath(value string) bool {
	if strings.HasPrefix(value, "/") || strings.HasPrefix(value, "\\") {
		return true
	}
	return len(value) >= 3 && value[1] == ':' && (value[2] == '/' || value[2] == '\\')
}

func markdownIssueText(value string) string {
	value = strings.ReplaceAll(value, "\r\n", "\n")
	value = strings.ReplaceAll(value, "\r", "\n")
	value = strings.ReplaceAll(value, "\\", "\\\\")
	value = strings.ReplaceAll(value, "&", "&amp;")
	value = strings.ReplaceAll(value, "<", "&lt;")
	value = strings.ReplaceAll(value, ">", "&gt;")
	value = strings.ReplaceAll(value, "|", "\\|")
	value = strings.ReplaceAll(value, "`", "\\`")
	value = strings.ReplaceAll(value, "[", "\\[")
	value = strings.ReplaceAll(value, "]", "\\]")
	value = strings.ReplaceAll(value, "*", "\\*")
	value = strings.ReplaceAll(value, "_", "\\_")
	value = strings.ReplaceAll(value, "~", "\\~")
	return strings.ReplaceAll(value, "\n", "<br>")
}

func markdownIssueCode(value string) string {
	value = strings.ReplaceAll(value, "\r\n", " ")
	value = strings.NewReplacer("\r", " ", "\n", " ", "&", "&amp;", "<", "&lt;", ">", "&gt;", "|", "&#124;").Replace(value)
	longest := 0
	current := 0
	for _, character := range value {
		if character == '`' {
			current++
			longest = max(longest, current)
		} else {
			current = 0
		}
	}
	fence := strings.Repeat("`", longest+1)
	return fence + value + fence
}

func escapeIssueLinkURL(value string) string {
	return strings.NewReplacer(
		"\r", "%0D",
		"\n", "%0A",
		"\t", "%09",
		" ", "%20",
		"(", "%28",
		")", "%29",
		"[", "%5B",
		"]", "%5D",
		"\\", "%5C",
		"\"", "%22",
		"<", "%3C",
		">", "%3E",
	).Replace(value)
}
